apiVersion: k3d.io/v1alpha3
kind: Simple
# image: default k3s version
servers: 1
agents: 3
ports:
  - port: 0.0.0.0:83:80
    nodeFilters:
      - agent:0:direct
  - port: 0.0.0.0:446:443
    nodeFilters:
      - agent:0:direct
  - port: 0.0.0.0:5056:53/udp
    nodeFilters:
      - agent:0:direct
options:
  k3d:
    wait: true
    timeout: 1m0s
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik,servicelb,metrics-server
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
