apiVersion: k3d.io/v1alpha3
kind: Simple
name: k3s-k8gb-disco2
servers: 1
agents: 1
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
image: docker.io/rancher/k3s:latest
network: nw03
ports:
  - port: 0.0.0.0:8443:443
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:8080:80
    nodeFilters:
      - loadbalancer
env:
  - envVar: bar=baz
    nodeFilters:
      - all
options:
  k3d:
    wait: true
    timeout: 1m0s
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --no-deploy=metrics-server
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
      - label: foo=bar
        nodeFilters:
          - loadbalancer
