name: Multi cluster; two pairs of clusters on two isolated networks

on:
  [workflow_dispatch, push]
jobs:
  k3d-multicluster-demo:
    name: Two pairs of clusters on two isolated networks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Create 1st Cluster in 172.18.0.0/16"
        with:
          cluster-name: "test-cluster-1"
          args: >-
            -p "80:80@agent:0:direct"
            -p "443:443@agent:0:direct"
            -p "5053:53/udp@agent:0:direct"
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
            --network "nw01"

      - uses: ./
        name: "Create 2nd Cluster in 172.18.0.0/16"
        with:
          cluster-name: "test-cluster-2"
          args: >-
            -p "81:80@agent:0:direct"
            -p "444:443@agent:0:direct"
            -p "5054:53/udp@agent:0:direct"
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
            --network "nw01"

      - uses: ./
        name: "Create 1st Cluster in 172.19.0.0/16"
        with:
          cluster-name: "test-cluster-3"
          args: >-
            -p "82:80@agent:0:direct"
            -p "445:443@agent:0:direct"
            -p "5055:53/udp@agent:0:direct"
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
            --network "nw02"

      - uses: ./
        name: "Create 2nd Cluster in 172.19.0.0/16"
        with:
          cluster-name: "test-cluster-4"
          args: >-
            -p "83:80@agent:0:direct"
            -p "446:443@agent:0:direct"
            -p "5056:53/udp@agent:0:direct"
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
            --network "nw02"

      - name: Cluster info
        run: |
          kubectl cluster-info --context k3d-test-cluster-1
          kubectl cluster-info --context k3d-test-cluster-2
          kubectl cluster-info --context k3d-test-cluster-3
          kubectl cluster-info --context k3d-test-cluster-4

      - name: Nodes
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-2
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-3
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-4
          kubectl get nodes -o wide

      - name: Network
        run: |
          docker network list
          docker network inspect nw01
          docker network inspect nw02
