name: Single cluster on default network with config

on:
  [workflow_dispatch, push]
jobs:
  k3d-single-cluster-demo:
    name: Single cluster on default network with config
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Create single k3d Cluster"
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --config=.github/workflows/assets/1.yaml
      - name: Cluster info
        run: |
          kubectl cluster-info --context k3d-test-cluster-1
      - name: Nodes
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          kubectl get nodes -o wide
      - name: Network
        run: docker network inspect nw01
